apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-demo
  namespace: argocd
project: default
source:
  repoURL: 'https://github.com/kdlug/argocd-demo'
  path: applications
  targetRevision: HEAD
  directory:
    recurse: true
destination:
  server: 'https://kubernetes.default.svc'
  namespace: argocd
syncPolicy:
  automated: {}

