apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echoserver
  namespace: argocd # namespace of application itself
spec:
  project: default
  source:
    repoURL: https://github.com/kdlug/argocd-demo
    targetRevision: HEAD
    path: applications/echoserver
    #directory:
    #  recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
